all:
	mkdir -p generated
	pandoc -s -S --toc src/*.md -o generated/massive-docs.html
	pandoc -s -S --toc src/*.md -o generated/massive-docs.epub
	pandoc -s -S --toc src/*.md -o generated/massive-docs.md
